services:
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=test
    network_mode: "host"
    env_file:
      - ./hadoop.env

  spark-worker:
    image: apache/spark:3.5.4
    container_name: spark-worker
    network_mode: "host"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://129.74.152.201:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4g
      - SPARK_DRIVER_MEMORY=2g
      - SPARK_EXECUTOR_MEMORY=2g
      - SPARK_WORKER_OPTS="-Dspark.worker.cleanup.enabled=true"
      - SPARK_LOG_LEVEL=DEBUG
    command: "/bin/bash -c '/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://129.74.152.201:7077 --webui-port 8081'"
    depends_on:
      - datanode

volumes:
  hadoop_datanode:
