version: "1"

services:
  spark-master:
    image: apache/spark:3.5.4
    container_name: spark-master
    network_mode: "host"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=129.74.152.201
      - SPARK_PUBLIC_DNS=129.74.152.201
      - SPARK_LOCAL_IP=129.74.152.201
      - SPARK_CONF_DIR=/opt/spark/conf
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
