services:
  spark-worker:
    image: apache/spark:3.5.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://${MASTER_SPARK}
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4g
      - SPARK_DRIVER_MEMORY=2g
      - SPARK_EXECUTOR_MEMORY=2g
      - SPARK_WORKER_OPTS="-Dspark.worker.cleanup.enabled=true"
      - SPARK_LOG_LEVEL=DEBUG
    volumes:
    - ./../spark-app:/opt/spark/work-dir
    command: "/bin/bash -c '/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://${MASTER_SPARK} --webui-port 8081'"
    networks:
      - spark-network
networks:
  spark-network:
    driver: bridge